import type { Property, PropertyType } from "./types";
import { asset } from "./asset";

/**
 * Banques d'images thématiques, servies en local depuis `public/images`.
 * (Photos de démonstration ; en production elles viendront de la base.)
 */
const IMAGE_POOLS: Record<PropertyType, string[]> = {
  appartement: [
    "/images/appartement-1.jpg",
    "/images/appartement-2.jpg",
    "/images/appartement-3.jpg",
    "/images/appartement-4.jpg",
    "/images/appartement-5.jpg",
  ],
  villa: [
    "/images/villa-1.jpg",
    "/images/villa-2.jpg",
    "/images/villa-3.jpg",
    "/images/villa-4.jpg",
  ],
  terrain: [
    "/images/terrain-1.jpg",
    "/images/terrain-2.jpg",
    "/images/terrain-3.jpg",
    "/images/terrain-4.jpg",
  ],
  garage: [
    "/images/garage-1.jpg",
    "/images/garage-2.jpg",
    "/images/garage-3.jpg",
    "/images/garage-4.jpg",
  ],
};

/**
 * Renvoie une galerie d'images thématiques pour un type de bien.
 * `variant` décale le point de départ afin de varier les photos d'une
 * annonce à l'autre au sein d'un même type.
 */
function imgs(type: PropertyType, variant = 0, count = 4): string[] {
  const pool = IMAGE_POOLS[type];
  return Array.from({ length: Math.min(count, pool.length) }, (_, i) =>
    asset(pool[(variant + i) % pool.length]),
  );
}

/**
 * Données de démonstration.
 * En production, elles proviendront de la base (Supabase/Postgres).
 * La forme des objets correspond exactement au type `Property`.
 */
export const properties: Property[] = [
  {
    id: "1",
    slug: "villa-contemporaine-hydra-alger",
    type: "villa",
    transaction: "vente",
    status: "en_cours",
    title: "Villa contemporaine à Hydra",
    description:
      "Villa d'architecte baignée de lumière, sur les hauteurs d'Hydra. Vastes pièces de réception ouvertes sur un jardin paysager, finitions haut de gamme et garage double. Une adresse rare dans l'un des quartiers les plus prisés d'Alger.",
    city: "Hydra, Alger",
    lat: 36.7456,
    lng: 3.0386,
    price: 95000000,
    currency: "DA",
    surface: 320,
    featured: true,
    acteNotarie: true,
    livretFoncier: true,
    details: { pieces: 8, chambres: 5, etage: 0 },
    images: imgs("villa", 0),
    createdAt: "2026-05-02T10:00:00Z",
  },
  {
    id: "2",
    slug: "appartement-f4-oran-front-de-mer",
    type: "appartement",
    transaction: "vente",
    status: "en_cours",
    title: "Appartement F4 vue mer",
    description:
      "Bel F4 traversant au 6e étage d'une résidence sécurisée, avec balcon filant face à la baie d'Oran. Cuisine équipée, double séjour et place de parking en sous-sol. Lumineux toute la journée.",
    city: "Oran",
    lat: 35.6987,
    lng: -0.6349,
    price: 28000000,
    currency: "DA",
    surface: 110,
    featured: true,
    acteNotarie: true,
    livretFoncier: false,
    details: { pieces: 4, chambres: 3, etage: 6 },
    images: imgs("appartement", 0),
    createdAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "3",
    slug: "terrain-constructible-tipaza",
    type: "terrain",
    transaction: "vente",
    status: "en_cours",
    title: "Terrain constructible à Tipaza",
    description:
      "Parcelle plate et viabilisée à quelques minutes de la mer, idéale pour un projet de villa ou de petit collectif. Façade large, accès direct par route goudronnée. Permis de construire envisageable.",
    city: "Tipaza",
    lat: 36.5894,
    lng: 2.4474,
    price: 18000000,
    currency: "DA",
    surface: 600,
    featured: false,
    acteNotarie: true,
    livretFoncier: true,
    details: { constructible: true },
    images: imgs("terrain", 0),
    createdAt: "2026-04-21T10:00:00Z",
  },
  {
    id: "4",
    slug: "appartement-f3-location-alger-centre",
    type: "appartement",
    transaction: "location",
    status: "en_cours",
    title: "F3 meublé au centre d'Alger",
    description:
      "Appartement F3 entièrement meublé et rénové, en plein centre, proche de toutes commodités. Idéal pour un cadre ou une famille. Disponible immédiatement, charges comprises.",
    city: "Alger Centre",
    lat: 36.7753,
    lng: 3.0601,
    price: 80000,
    currency: "DA",
    surface: 75,
    featured: false,
    acteNotarie: false,
    livretFoncier: false,
    details: { pieces: 3, chambres: 2, etage: 3 },
    images: imgs("appartement", 1),
    createdAt: "2026-05-28T10:00:00Z",
  },
  {
    id: "5",
    slug: "garage-box-ferme-bab-ezzouar",
    type: "garage",
    transaction: "location",
    status: "en_cours",
    title: "Box fermé à Bab Ezzouar",
    description:
      "Garage box individuel fermé et sécurisé, accès facile, dans une résidence gardée. Convient pour véhicule ou stockage. Contrat de location souple.",
    city: "Bab Ezzouar, Alger",
    lat: 36.7212,
    lng: 3.1846,
    price: 15000,
    currency: "DA",
    surface: 18,
    featured: false,
    acteNotarie: false,
    livretFoncier: false,
    details: {},
    images: imgs("garage", 0),
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "6",
    slug: "villa-echange-constantine",
    type: "villa",
    transaction: "echange",
    status: "en_cours",
    title: "Villa R+1 à échanger",
    description:
      "Villa R+1 avec garage et cour, dans un quartier résidentiel calme de Constantine. Le propriétaire étudie un échange contre un bien sur Alger ou Oran.",
    city: "Constantine",
    lat: 36.365,
    lng: 6.6147,
    price: 42000000,
    currency: "DA",
    surface: 180,
    featured: true,
    acteNotarie: true,
    livretFoncier: true,
    details: {
      pieces: 6,
      chambres: 4,
      etage: 0,
      trocSouhaite:
        "Échange souhaité contre un appartement F4/F5 sur Alger (Hydra, Ben Aknoun) ou une villa à Oran, avec ou sans soulte.",
    },
    images: imgs("villa", 1),
    createdAt: "2026-05-18T10:00:00Z",
  },
  {
    id: "7",
    slug: "appartement-paris-investissement",
    type: "appartement",
    transaction: "vente",
    status: "en_cours",
    title: "Studio à Paris 11e",
    description:
      "Studio optimisé proche de la Bastille, parfait pour un investissement locatif. Immeuble en pierre de taille, faibles charges, fort potentiel de rendement.",
    city: "Paris 11e, France",
    lat: 48.8578,
    lng: 2.3792,
    price: 245000,
    currency: "EUR",
    surface: 26,
    featured: false,
    acteNotarie: true,
    livretFoncier: false,
    details: { pieces: 1, chambres: 0, etage: 4 },
    images: imgs("appartement", 2),
    createdAt: "2026-04-30T10:00:00Z",
  },
  {
    id: "8",
    slug: "villa-piscine-montreal",
    type: "villa",
    transaction: "vente",
    status: "en_cours",
    title: "Maison avec piscine à Montréal",
    description:
      "Maison familiale spacieuse avec piscine et grand terrain arboré, dans un quartier résidentiel recherché. Sous-sol aménagé, double garage, proche écoles et commerces.",
    city: "Montréal, Canada",
    lat: 45.5019,
    lng: -73.5674,
    price: 720000,
    currency: "USD",
    surface: 260,
    featured: false,
    acteNotarie: true,
    livretFoncier: false,
    details: { pieces: 9, chambres: 5, etage: 0 },
    images: imgs("villa", 2),
    createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "9",
    slug: "terrain-agricole-blida",
    type: "terrain",
    transaction: "vente",
    status: "vendu",
    title: "Terrain agricole à Blida",
    description:
      "Belle parcelle agricole irriguée au pied de l'Atlas blidéen, idéale pour l'arboriculture. Point d'eau présent. (Bien déjà vendu — conservé pour l'historique.)",
    city: "Blida",
    lat: 36.4703,
    lng: 2.8277,
    price: 9000000,
    currency: "DA",
    surface: 2500,
    featured: false,
    acteNotarie: true,
    livretFoncier: true,
    details: { constructible: false },
    images: imgs("terrain", 1),
    createdAt: "2026-02-08T10:00:00Z",
  },
  {
    id: "10",
    slug: "appartement-f5-setif-neuf",
    type: "appartement",
    transaction: "vente",
    status: "en_cours",
    title: "F5 neuf à Sétif",
    description:
      "Grand F5 jamais habité dans une promotion immobilière récente, prestations modernes, ascenseur et parking. Quartier en plein essor, proche de l'université.",
    city: "Sétif",
    lat: 36.1898,
    lng: 5.4108,
    price: 24000000,
    currency: "DA",
    surface: 130,
    featured: false,
    acteNotarie: true,
    livretFoncier: true,
    details: { pieces: 5, chambres: 3, etage: 2 },
    images: imgs("appartement", 3),
    createdAt: "2026-06-05T10:00:00Z",
  },
  {
    id: "11",
    slug: "garage-vente-oran-centre",
    type: "garage",
    transaction: "vente",
    status: "en_cours",
    title: "Garage en plein centre d'Oran",
    description:
      "Garage en rez-de-chaussée d'immeuble, accès direct sur rue, fort potentiel (stockage, atelier ou stationnement). Rare dans ce secteur très demandé.",
    city: "Oran Centre",
    lat: 35.6976,
    lng: -0.6308,
    price: 3500000,
    currency: "DA",
    surface: 22,
    featured: false,
    acteNotarie: true,
    livretFoncier: false,
    details: {},
    images: imgs("garage", 1),
    createdAt: "2026-05-22T10:00:00Z",
  },
  {
    id: "12",
    slug: "appartement-echange-annaba",
    type: "appartement",
    transaction: "echange",
    status: "en_cours",
    title: "F4 à échanger à Annaba",
    description:
      "Appartement F4 lumineux proche de la corniche, en bon état. Le propriétaire recherche un échange contre un bien équivalent sur Alger.",
    city: "Annaba",
    lat: 36.9,
    lng: 7.7667,
    price: 22000000,
    currency: "DA",
    surface: 95,
    featured: false,
    acteNotarie: true,
    livretFoncier: false,
    details: {
      pieces: 4,
      chambres: 3,
      etage: 5,
      trocSouhaite:
        "Recherche un F3/F4 sur Alger (Kouba, Bir Mourad Raïs) en échange, soulte possible selon le bien.",
    },
    images: imgs("appartement", 4),
    createdAt: "2026-06-09T10:00:00Z",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}
